version: '3.3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - personal
      - anime
    environment:
      PERSONAL_PORT: ${PERSONAL_PORT}
    networks:
      - network

  personal:
    container_name: personal
    image: fishfinna/personal:latest
    ports:
      - "9000:9000"
    environment:
      VITE_HOST: ${HOST}
      VITE_PORT: ${PERSONAL_PORT}
    networks:
      - network
    
  anime:
    container_name: anime
    image: fishfinna/anime:latest
    ports:
      - "8080:8080"
    networks:
      - network

networks:
  network:
    driver: bridge
